#!/usr/bin/env bash

export SMF_CONFIG=$(for f in /etc/simple-mail-forwarder/mail.d/*.txt; do cat "${f}"; echo; done)
export SMF_DOMAIN=$(cat /etc/simple-mail-forwarder/domain.txt 2>/dev/null)

YAML=$(cat <<'EOF'
version: "3.6"
services:
  mail:
    container_name: simple-mail-forwarder
    image: zixia/simple-mail-forwarder
    restart: unless-stopped
    volumes:
      - /etc/simple-mail-forwarder/dkim:/var/db/dkim
    environment:
      SMF_CONFIG: "${SMF_CONFIG}"
      SMF_DOMAIN: "${SMF_DOMAIN}"
    ports:
      - "25:25"
EOF
)

echo "$YAML" | docker-compose -f - down
echo "$YAML" | docker-compose -f - up
